import type { Tables } from "./db/database.types";

// -----------------------------------------------------------------------------
// Base entity row aliases (generated by Supabase code-gen)
// -----------------------------------------------------------------------------
// Creating short aliases keeps every DTO definition coupled to the database
// schema while remaining concise.

export type FlashcardRow = Tables<"flashcards">;
export type GenerationRow = Tables<"generations">;
export type GenerationErrorLogRow = Tables<"generation_error_logs">;
export type SourceType = FlashcardRow["source_type"];

// -----------------------------------------------------------------------------
// Generic helpers
// -----------------------------------------------------------------------------

/** Pagination metadata shared by list endpoints. */
export interface PaginationDto {
  total: number;
  page: number;
  limit: number;
  pages: number;
}

/** Generic wrapper for paginated responses. */
export interface PaginatedResponseDto<T> {
  data: T[];
  pagination: PaginationDto;
}

// -----------------------------------------------------------------------------
// Generations
// -----------------------------------------------------------------------------

/** Request body for POST `/api/generations` */
export interface StartGenerationRequestDto {
  /** Text content the AI service will use to generate flashcards */
  source_text: string;
}

/** Lightweight flashcard object returned as a proposal straight after generation. */
export type FlashcardProposalDto = Pick<FlashcardRow, "id" | "front_text" | "back_text" | "source_type">;

/** Response body for POST `/api/generations` */
export interface StartGenerationResponseDto
  extends Pick<
    GenerationRow,
    "id" | "user_id" | "source_text_length" | "generation_duration" | "created_at" | "flashcards_count"
  > {
  flashcards_proposals: FlashcardProposalDto[];
}

/** Response body for GET `/api/generations/{id}` */
export interface GenerationDetailResponseDto
  extends Pick<
    GenerationRow,
    "id" | "user_id" | "source_text_length" | "generation_duration" | "created_at" | "flashcards_count"
  > {
  flashcards: FlashcardDto[];
}

/** Generation object displayed in list views. */
export type GenerationSummaryDto = Pick<
  GenerationRow,
  "id" | "source_text_length" | "created_at" | "flashcards_count" | "accepted_unedited_count" | "accepted_edited_count"
>;

/** Response body for GET `/api/generations` */
export type GenerationsListResponseDto = PaginatedResponseDto<GenerationSummaryDto>;

// -----------------------------------------------------------------------------
// Accepting generated flashcards
// -----------------------------------------------------------------------------

/** Flashcard selected by the user for acceptance (may have been edited). */
export type FlashcardAcceptDto = Pick<
  FlashcardRow,
  "id" | "front_text" | "back_text" | "source_type" | "generation_id"
>;

/** Request body for POST `/api/generations/{id}/accept` */
export interface AcceptGenerationFlashcardsRequestDto {
  flashcards: FlashcardAcceptDto[];
}

/** Response body for POST `/api/generations/{id}/accept` */
export interface AcceptGenerationFlashcardsResponseDto {
  accepted_count: number;
  flashcards: FlashcardDto[];
}

// -----------------------------------------------------------------------------
// Flashcards
// -----------------------------------------------------------------------------

/** Canonical flashcard representation exposed by read endpoints. */
export type FlashcardDto = Pick<
  FlashcardRow,
  "id" | "front_text" | "back_text" | "created_at" | "updated_at" | "source_type" | "generation_id"
>;

/** DTO used when creating new flashcards manually*/
export type FlashcardCreateDto = Pick<FlashcardRow, "front_text" | "back_text" | "source_type" | "generation_id">;

/** Request body for POST `/api/flashcards` */
export interface FlashcardsCreateRequestDto {
  flashcards: FlashcardCreateDto[];
}

/** Response body for POST `/api/flashcards` */
export interface FlashcardsCreateResponseDto {
  flashcards: FlashcardDto[];
}

/** Response body for GET `/api/flashcards` */
export type FlashcardsListResponseDto = PaginatedResponseDto<FlashcardDto>;

/** Response body for GET `/api/flashcards/{id}` */
export type FlashcardDetailResponseDto = FlashcardDto & {
  user_id: FlashcardRow["user_id"];
};

/** Request body for PATCH `/api/flashcards/{id}` */
export type FlashcardUpdateRequestDto = Partial<Pick<FlashcardRow, "front_text" | "back_text">>;

// -----------------------------------------------------------------------------
// Generation Error Logs
// -----------------------------------------------------------------------------

/** Reduced error log object used in list responses (without `source_text`). */
export type GenerationErrorLogSummaryDto = Pick<
  GenerationErrorLogRow,
  "id" | "user_id" | "model" | "source_text_length" | "error_code" | "error_message" | "created_at"
>;

/** Response body for GET `/api/generation-error-logs` */
export type GenerationErrorLogsListResponseDto = PaginatedResponseDto<GenerationErrorLogSummaryDto>;

/** Response body for GET `/api/generation-error-logs/{id}` */
export type GenerationErrorLogDetailDto = GenerationErrorLogRow;
